#The basic size of the box (x*x)
size: 10

#If the search radius is too high, your server can get severe lag / can crash
SearchRadius: 20

#The delay before tp a player inside his box after create his world in tick (20 tick = 1 sec)
tpDelay: 30

#if every player needs to have the same seed / map, put it here, else put None
baseSeed: "None"

#Choose if you want to announce every advancement (true or false)
showAllAdvancements: false

#The time before the invitation expire (in second)
inviteTime: 60

#Define the maximum number of player a box can have (the owner didn't count as a member)
memberLimit: 5

#Define how many block the border is going to expand with every advancement
borderExpand: 2